global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - rules/slo-alerts.yml
  - rules/infrastructure-alerts.yml
scrape_configs:
  - job_name: banking-app
    metrics_path: /metrics
    static_configs:
      - targets: ["banking-app-service.banking-dev.svc.cluster.local:80"]
